export const MusicUsageData = [
    {
        "title": "General Info",
        "text": [
            "My music is available to be used in your YouTube and Twitch content, many of which come with certain restrictions.",

            "One particular restriction involves YouTube content ID, which allows me to prevent a YouTube video from being monetizable by the channel if it detects my music within it. Instead, all ad revenue that would be generated by the video goes to me. This does not harm your channel, and you will not receive a copyright strike or anything similar unless my music is being used maliciously (fraud, theft, etc).",

            "Visit my music page, which lists my entire discography and how you may use each track in your online content!",

            "If you would like to use my music for commercial use (film, advertising, TV, video games, etc) or if you are unclear about anything, please feel free to contact me. Please describe your request in detail.",
        ],
        "code": []
    },
    {
        "title": "How To Credit",
        "text": [
            "You can credit me by putting the following in the description of your video/stream:",
        ],
        "code": [
            "Music by Similar Outskirts",
            "https://similaroutskirts.com",
            "https://soundcloud.com/similar-outskirts",
            "https://x.com/Sim_Out_",
            "https://youtube.com/SimilarOutskirts",
        ]
    },
    {
        "title": "Custom Maps/Charts For Rhythm Games",
        "text": [
            "Feel free to make custom rhythm game maps/charts in the following games. These should be fan-made. Commercial use is NOT allowed. If you are a developer looking to officially release my music along with a map/chart in your game, feel free to contact me.",
        ],
        "code": [
            "- A Dance of Fire and Ice",
            "- Clone Hero",
            "- osu!",
            "- Project Arrythmia",
            "- Rhythm Doctor",
            "- Soundodger 2",
        ]
    },
]