export const MusicData = [
  {
    "id": 1,
    "title": "Technology",
    "subtitle": "",
    "release_date": "2014-4-19",
    "length": 286,
    "keysig": ["A / F#m"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-technology",
    "art": "https://i1.sndcdn.com/artworks-000201064877-ma7nd4-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 2,
    "title": "Feel The Buzz",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-7-19",
    "length": 252,
    "keysig": ["E / C#m"],
    "tempo": [105, 175],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/sub-sound-feel-the-buzz",
    "art": "https://i1.sndcdn.com/artworks-000201108064-pbjh4c-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 3,
    "title": "Cyborg Meltdown",
    "subtitle": "",
    "release_date": "2014-7-21",
    "length": 259,
    "keysig": ["D / Bm"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-cyborg",
    "art": "https://i1.sndcdn.com/artworks-000201108179-trs4dq-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 4,
    "title": "Boom!",
    "subtitle": "",
    "release_date": "2014-7-29",
    "length": 217,
    "keysig": ["C / Am"],
    "tempo": [130],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-boom-the",
    "art": "https://i1.sndcdn.com/artworks-000201108332-a1a4c1-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 5,
    "title": "Snowball Fight",
    "subtitle": "",
    "release_date": "2014-8-18",
    "length": 232,
    "keysig": ["G / Em"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-snowball-fight",
    "art": "https://i1.sndcdn.com/artworks-000201108469-ewix52-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 6,
    "title": "Jubilant Skydive",
    "subtitle": "",
    "release_date": "2014-9-15",
    "length": 264,
    "keysig": ["F / Dm", "G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-jubilant",
    "art": "https://i1.sndcdn.com/artworks-000201108577-7ke5xc-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 7,
    "title": "Interstellar",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-11-2",
    "length": 206,
    "keysig": ["G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/laszlo-interstellar-similar",
    "art": "https://i1.sndcdn.com/artworks-000201108680-1972jr-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 8,
    "title": "Radiation",
    "subtitle": "",
    "release_date": "2014-11-21",
    "length": 248,
    "keysig": ["C / Am"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-radiation",
    "art": "https://i1.sndcdn.com/artworks-000201108735-zomr6p-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 9,
    "title": "When You Sleep",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-12-23",
    "length": 211,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/vau-boy-when-you-sleep-2014-ft",
    "art": "https://i1.sndcdn.com/artworks-000201108789-sbmywn-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 10,
    "title": "I'm Here",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-6-12",
    "length": 208,
    "keysig": ["B / G#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/im-here-remix",
    "art": "https://i1.sndcdn.com/artworks-000201108920-ha9ybf-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 11,
    "title": "The Time Traveller",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-12-12",
    "length": 235,
    "keysig": ["A / F#m"],
    "tempo": [140, 175],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/getsix-the-time-traveller-similar-outskirts-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109218-vmy3sr-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 12,
    "title": "Epiphany",
    "subtitle": "",
    "release_date": "2015-12-31",
    "length": 221,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/epiphany",
    "art": "https://i1.sndcdn.com/artworks-000201109282-2dk1fu-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 13,
    "title": "Senses Overload",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-1-23",
    "length": 259,
    "keysig": ["F# / D#m"],
    "tempo": [174],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/senses-overload-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109366-dwo6l9-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 14,
    "title": "Blast Off",
    "subtitle": "",
    "release_date": "2016-2-13",
    "length": 214,
    "keysig": ["C / Am"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/blast-off",
    "art": "https://i1.sndcdn.com/artworks-000201109403-15wjb7-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 15,
    "title": "Choreography",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 273,
    "keysig": ["D / Bm"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-choreography-1",
    "art": "https://i1.sndcdn.com/artworks-r9HgdKj4YNjUuUwy-GZUvFQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 16,
    "title": "Whiplash",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 229,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-whiplash-1",
    "art": "https://i1.sndcdn.com/artworks-r9HgdKj4YNjUuUwy-GZUvFQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 17,
    "title": "Awake and Unafraid",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 227,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-awake-and-unafraid",
    "art": "https://i1.sndcdn.com/artworks-r9HgdKj4YNjUuUwy-GZUvFQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 18,
    "title": "Roller Coaster",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 262,
    "keysig": ["A / F#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-roller-coaster",
    "art": "https://i1.sndcdn.com/artworks-r9HgdKj4YNjUuUwy-GZUvFQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 19,
    "title": "Apollo",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-6-4",
    "length": 245,
    "keysig": ["A# / Gm"],
    "tempo": [145],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/apollo-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109476-uls3g6-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 20,
    "title": "Alone",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-6-30",
    "length": 242,
    "keysig": ["D / Bm"],
    "tempo": [105],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/alone-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109531-mtar1e-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 21,
    "title": "Thunderbolt",
    "subtitle": "",
    "release_date": "2016-10-8",
    "length": 278,
    "keysig": ["A# / Gm"],
    "tempo": [155],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/thunderbolt",
    "art": "https://i1.sndcdn.com/artworks-000201109566-uto803-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 22,
    "title": "Cyber Talk",
    "subtitle": "",
    "release_date": "2016-10-24",
    "length": 258,
    "keysig": ["B / G#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-cyber-talk",
    "art": "https://i1.sndcdn.com/artworks-000201109615-ea0k9n-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 23,
    "title": "Party",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-12-4",
    "length": 257,
    "keysig": ["A# / Gm"],
    "tempo": [128],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/party-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109805-heszyu-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 24,
    "title": "Stay Classy",
    "subtitle": "w/ Redshift",
    "release_date": "2016-12-21",
    "length": 251,
    "keysig": ["D / Bm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": true,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/redshift-similar-outskirts-stay-classy",
    "art": "https://i1.sndcdn.com/artworks-000199509544-gocf3d-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 25,
    "title": "Aishiteru Banzai!",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-1-10",
    "length": 262,
    "keysig": ["E / C#m"],
    "tempo": [100],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/aishiteru-banzai-remix",
    "art": "https://i1.sndcdn.com/artworks-000202192302-2jtlvg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 26,
    "title": "Nanamori",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-2-5",
    "length": 217,
    "keysig": ["A# / Gm"],
    "tempo": [160],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/nanamori-remix",
    "art": "https://i1.sndcdn.com/artworks-000206361585-o76n59-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 27,
    "title": "Starchaser",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-2-15",
    "length": 350,
    "keysig": ["D# / Cm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/starchaser-similar-outskirts-remix",
    "art": "https://i1.sndcdn.com/artworks-000207914906-wpe4v0-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 28,
    "title": "Burnout",
    "subtitle": "",
    "release_date": "2017-3-7",
    "length": 293,
    "keysig": ["G# / Fm"],
    "tempo": [174],
    "label": "Umbra Collective",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/umbracollective/similar-outskirts-burnout",
    "art": "https://i1.sndcdn.com/artworks-000211074842-oekjck-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 29,
    "title": "Guilty Eyes Fever",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-4-13",
    "length": 299,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/guilty-eyes-fever-remix",
    "art": "https://i1.sndcdn.com/artworks-000217654503-mqffcv-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 30,
    "title": "No Stopping Us",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-5-28",
    "length": 262,
    "keysig": ["E / C#m"],
    "tempo": [160],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/no-stopping-us-remix",
    "art": "https://i1.sndcdn.com/artworks-000224736337-vmtyfc-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 31,
    "title": "Atlantis",
    "subtitle": "",
    "release_date": "2017-6-19",
    "length": 262,
    "keysig": ["A / F#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-atlantis",
    "art": "https://i1.sndcdn.com/artworks-000229273632-z7qd0k-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 32,
    "title": "Phantom",
    "subtitle": "",
    "release_date": "2017-7-10",
    "length": 253,
    "keysig": ["F / Dm"],
    "tempo": [128],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/SimilarOutskirtsPhantom",
    "art": "https://i1.sndcdn.com/artworks-000232933218-ffbdjf-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 33,
    "title": "Our World",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-8-14",
    "length": 339,
    "keysig": ["D / Bm"],
    "tempo": [120],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/our-world-remix",
    "art": "https://i1.sndcdn.com/artworks-000238230107-oo7d27-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 34,
    "title": "Lonely Tuning",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-8-24",
    "length": 293,
    "keysig": ["D# / Cm"],
    "tempo": [100],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/lonely-tuning-remix",
    "art": "https://i1.sndcdn.com/artworks-000239720248-34b556-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 35,
    "title": "Wait For Me",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-9-1",
    "length": 300,
    "keysig": ["G / Em", "A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/wait-for-me-remix",
    "art": "https://i1.sndcdn.com/artworks-000240844547-41zu9t-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 36,
    "title": "Gadget",
    "subtitle": "",
    "release_date": "2017-10-13",
    "length": 325,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/gadget",
    "art": "https://i1.sndcdn.com/artworks-000247059101-t8kq8m-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 37,
    "title": "Daring!!",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2018-1-10",
    "length": 241,
    "keysig": ["F / Dm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/daring-remix",
    "art": "https://i1.sndcdn.com/artworks-000283273985-xul607-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 38,
    "title": "Daredevil",
    "subtitle": "",
    "release_date": "2018-2-23",
    "length": 317,
    "keysig": ["A# / Gm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://i1.sndcdn.com/artworks-000296488260-kasjmt-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 39,
    "title": "Space Combat",
    "subtitle": "",
    "release_date": "2018-2-23",
    "length": 280,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://i1.sndcdn.com/artworks-000296488260-kasjmt-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 40,
    "title": "Triumphant",
    "subtitle": "",
    "release_date": "2018-2-23",
    "length": 266,
    "keysig": ["G# / Fm"],
    "tempo": [90],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://i1.sndcdn.com/artworks-000296488260-kasjmt-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 41,
    "title": "Street Race",
    "subtitle": "",
    "release_date": "2018-2-23",
    "length": 246,
    "keysig": ["G / Em"],
    "tempo": [160],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://i1.sndcdn.com/artworks-000296488260-kasjmt-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 42,
    "title": "Amber",
    "subtitle": "",
    "release_date": "2018-4-14",
    "length": 217,
    "keysig": ["D / Bm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/amber",
    "art": "https://i1.sndcdn.com/artworks-000335226591-f95qoa-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 43,
    "title": "HEROIC ADVENT",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2018-5-19",
    "length": 237,
    "keysig": ["G / Em"],
    "tempo": [182],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/heroic-advent-remix",
    "art": "https://i1.sndcdn.com/artworks-000478271904-2j4eds-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 44,
    "title": "Chaos",
    "subtitle": "",
    "release_date": "2018-6-8",
    "length": 256,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/chaos",
    "art": "https://i1.sndcdn.com/artworks-000358440750-81b39h-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 45,
    "title": "Xana",
    "subtitle": "",
    "release_date": "2018-7-27",
    "length": 247,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000380151171-3tuzlp-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 46,
    "title": "Horology",
    "subtitle": "",
    "release_date": "2018-8-3",
    "length": 280,
    "keysig": ["A# / Gm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 47,
    "title": "Time Leap",
    "subtitle": "",
    "release_date": "2018-8-3",
    "length": 294,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 48,
    "title": "Hourglass",
    "subtitle": "",
    "release_date": "2018-8-3",
    "length": 319,
    "keysig": ["C / Am", "D / Bm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 49,
    "title": "Cosmonaut",
    "subtitle": "",
    "release_date": "2018-9-29",
    "length": 227,
    "keysig": ["E / C#m"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/cosmonaut",
    "art": "https://i1.sndcdn.com/artworks-000412651857-ltvb57-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 50,
    "title": "Get High",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2018-10-26",
    "length": 242,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/get-high-remix",
    "art": "https://i1.sndcdn.com/artworks-000428915211-8uhojv-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 51,
    "title": "Whirlwind",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2019-2-1",
    "length": 201,
    "keysig": ["G# / Fm"],
    "tempo": [174],
    "label": "Rushdown",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/WRmxsSimilarOutskirts",
    "art": "https://i1.sndcdn.com/artworks-000481813899-zzqpur-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 52,
    "title": "Hey-Day Capriccio",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2019-3-5",
    "length": 249,
    "keysig": ["A# / Gm", "F / Dm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/hey-day-capriccio-remix",
    "art": "https://i1.sndcdn.com/artworks-000499165281-b3te9p-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 53,
    "title": "All Might",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2019-3-18",
    "length": 266,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://fanlink.tv/dandereremixes",
    "art": "https://i1.sndcdn.com/artworks-000505933815-p39pqa-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 54,
    "title": "Eternal",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2019-7-5",
    "length": 306,
    "keysig": ["D / Bm"],
    "tempo": [110],
    "label": "Independent",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://distrokid.com/hyperfollow/fokushi/eternal-remixed",
    "art": "https://i1.sndcdn.com/artworks-000562037337-mrsvh8-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 55,
    "title": "Abyss Dweller",
    "subtitle": "",
    "release_date": "2019-8-30",
    "length": 301,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/abyss-dweller",
    "art": "https://i1.sndcdn.com/artworks-000589915874-8jxu2i-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 56,
    "title": "Replay Attack",
    "subtitle": "",
    "release_date": "2019-9-19",
    "length": 252,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/ReplayAttack",
    "art": "https://i1.sndcdn.com/artworks-000600103214-127p9h-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 57,
    "title": "About Us",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2019-10-11",
    "length": 223,
    "keysig": ["E / C#m"],
    "tempo": [100],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/disero/au-simout",
    "art": "https://i1.sndcdn.com/artworks-000604999342-wm4czj-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 58,
    "title": "Stargazer",
    "subtitle": "",
    "release_date": "2019-10-18",
    "length": 269,
    "keysig": ["C / Am"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/stargazer",
    "art": "https://i1.sndcdn.com/artworks-000615084523-2nfdzm-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 59,
    "title": "For Me",
    "subtitle": "Intro",
    "release_date": "2019-11-22",
    "length": 116,
    "keysig": ["C / Am"],
    "tempo": [77],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/imagination-ep",
    "art": "https://i1.sndcdn.com/artworks-000636116902-kos305-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 60,
    "title": "Imagination",
    "subtitle": "",
    "release_date": "2019-11-22",
    "length": 248,
    "keysig": ["C / Am"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/imagination-ep",
    "art": "https://i1.sndcdn.com/artworks-000636116902-kos305-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 61,
    "title": "Daydream",
    "subtitle": "",
    "release_date": "2019-11-22",
    "length": 309,
    "keysig": ["D / Bm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/imagination-ep",
    "art": "https://i1.sndcdn.com/artworks-000636116902-kos305-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 62,
    "title": "Adventure",
    "subtitle": "",
    "release_date": "2019-11-22",
    "length": 288,
    "keysig": ["D / Bm"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/imagination-ep",
    "art": "https://i1.sndcdn.com/artworks-000636116902-kos305-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 63,
    "title": "Another World",
    "subtitle": "",
    "release_date": "2019-11-22",
    "length": 287,
    "keysig": ["G / Em"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/imagination-ep",
    "art": "https://i1.sndcdn.com/artworks-000636116902-kos305-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 64,
    "title": "Crescent",
    "subtitle": "",
    "release_date": "2020-4-11",
    "length": 225,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/Crescent",
    "art": "https://i1.sndcdn.com/artworks-qU3yxZg2j2KFzju0-BJqBzw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 65,
    "title": "Only Now",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2020-4-30",
    "length": 248,
    "keysig": ["A / F#m"],
    "tempo": [174],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/only-now-remix",
    "art": "https://i1.sndcdn.com/artworks-tyRLQ3KyLtK224wd-NgMjSg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 66,
    "title": "Simulation",
    "subtitle": "",
    "release_date": "2020-5-22",
    "length": 262,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/simulation",
    "art": "https://i1.sndcdn.com/artworks-bPMEoYGWdtxvsCLL-Pns6pA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 67,
    "title": "Pyre",
    "subtitle": "",
    "release_date": "2020-6-19",
    "length": 250,
    "keysig": ["F# / D#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/pyre",
    "art": "https://i1.sndcdn.com/artworks-PdaA7DgyvCHpuzva-xkVoQQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 68,
    "title": "Fire Bird",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2020-7-10",
    "length": 333,
    "keysig": ["A# / Gm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts-extra/fire-bird-remix",
    "art": "https://i1.sndcdn.com/artworks-9EA34IQ7AbN57H07-VTiVwQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 69,
    "title": "Eon",
    "subtitle": "",
    "release_date": "2020-7-31",
    "length": 275,
    "keysig": ["D / Bm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/eon",
    "art": "https://i1.sndcdn.com/artworks-RBCKyvOtv4xI8T1Y-uDF6EQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 70,
    "title": "If",
    "subtitle": "w/ Winamp Boys",
    "release_date": "2020-8-12",
    "length": 245,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "FORM",
    "remix": false,
    "official": true,
    "collaboration": true,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://anv5.artbyform.com",
    "art": "https://i1.sndcdn.com/artworks-IUrBEdMkZJEKrWq9-yIoKxA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 71,
    "title": "Titans",
    "subtitle": "Intro",
    "release_date": "2020-9-25",
    "length": 139,
    "keysig": ["G / Em"],
    "tempo": [75],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/TitansEP",
    "art": "https://i1.sndcdn.com/artworks-7FW7E8Q1zRqYjzRv-ktsq8Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 72,
    "title": "Colossal",
    "subtitle": "",
    "release_date": "2020-9-26",
    "length": 243,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/TitansEP",
    "art": "https://i1.sndcdn.com/artworks-7FW7E8Q1zRqYjzRv-ktsq8Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 73,
    "title": "Alloy",
    "subtitle": "",
    "release_date": "2020-9-27",
    "length": 233,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/TitansEP",
    "art": "https://i1.sndcdn.com/artworks-7FW7E8Q1zRqYjzRv-ktsq8Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 74,
    "title": "Cryotherapy",
    "subtitle": "",
    "release_date": "2020-9-28",
    "length": 251,
    "keysig": ["A# / Gm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/TitansEP",
    "art": "https://i1.sndcdn.com/artworks-7FW7E8Q1zRqYjzRv-ktsq8Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 75,
    "title": "Tectonic",
    "subtitle": "",
    "release_date": "2020-9-29",
    "length": 232,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/TitansEP",
    "art": "https://i1.sndcdn.com/artworks-7FW7E8Q1zRqYjzRv-ktsq8Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 76,
    "title": "Magnetic",
    "subtitle": "",
    "release_date": "2020-11-13",
    "length": 239,
    "keysig": ["A / F#m"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://similaroutskirts.fanlink.tv/magnetic",
    "art": "https://i1.sndcdn.com/artworks-MSEyMehpchbTOmUN-gbwLsw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 77,
    "title": "Shockwave",
    "subtitle": "",
    "release_date": "2020-12-11",
    "length": 230,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/ColourBassVol2",
    "art": "https://i1.sndcdn.com/artworks-thI2jpNuLSKkfjp7-iFtUFA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 78,
    "title": "All My Friends",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2020-12-25",
    "length": 216,
    "keysig": ["E / C#m"],
    "tempo": [120],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/all-my-friends-remix",
    "art": "https://i1.sndcdn.com/artworks-l4qS6WktssuVE6z2-DoQSyQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 79,
    "title": "Find My Way",
    "subtitle": "",
    "release_date": "2021-2-26",
    "length": 233,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/find-my-way",
    "art": "https://i1.sndcdn.com/artworks-BUjsMXCYpvsgVZwG-PDeALg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 80,
    "title": "Anomaly",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2021-3-30",
    "length": 193,
    "keysig": ["F / Dm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/anomaly-remix",
    "art": "https://i1.sndcdn.com/artworks-B3x2aIzkCQaRCIUy-yfeQpA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 81,
    "title": "In The Moment",
    "subtitle": "",
    "release_date": "2021-5-6",
    "length": 255,
    "keysig": ["D / Bm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/in-the-moment",
    "art": "https://i1.sndcdn.com/artworks-2zLCkYCmhlG1RSWD-toyqmw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 82,
    "title": "Unlimited",
    "subtitle": "",
    "release_date": "2021-6-25",
    "length": 227,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/unlimited",
    "art": "https://i1.sndcdn.com/artworks-w6KKiWNOJJzRDxRm-oIv8DA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 83,
    "title": "Hanging By A Thread",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2021-8-31",
    "length": 281,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/hanging-by-a-thread-remix",
    "art": "https://i1.sndcdn.com/artworks-Hv8SiJlmbKaY0KTu-YjJcwg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 84,
    "title": "Mastermind",
    "subtitle": "",
    "release_date": "2021-9-30",
    "length": 205,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "FiXT",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "https://www.fixtmusic.com/licensing/",
    "link": "https://outnow.io/t/mastermind",
    "art": "https://i1.sndcdn.com/artworks-wRmHaC3Ekutx-0-t200x200.png",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 85,
    "title": "Lotus Overture",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2021-10-15",
    "length": 233,
    "keysig": ["F / Dm"],
    "tempo": [150],
    "label": "Hot Panda Media",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://soundcloud.com/tenkitsunemusic/lotus-overture-similar",
    "art": "https://i1.sndcdn.com/artworks-eyydWFnnWuH2-0-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 86,
    "title": "Shade Soul",
    "subtitle": "",
    "release_date": "2021-11-5",
    "length": 234,
    "keysig": ["F / Dm"],
    "tempo": [140],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/ShadeSoul",
    "art": "https://i1.sndcdn.com/artworks-wRsabA8RAgbReXWh-5yZnnw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 87,
    "title": "Vessel",
    "subtitle": "",
    "release_date": "2021-11-5",
    "length": 228,
    "keysig": ["E / C#m"],
    "tempo": [140],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/ShadeSoul",
    "art": "https://i1.sndcdn.com/artworks-wRsabA8RAgbReXWh-5yZnnw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 88,
    "title": "Good Night",
    "subtitle": "Intro",
    "release_date": "2021-11-26",
    "length": 96,
    "keysig": ["D# / Cm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/headspace-ep",
    "art": "https://i1.sndcdn.com/artworks-D2rGnM5m3uqhPjbN-B117xw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 89,
    "title": "Headspace",
    "subtitle": "",
    "release_date": "2021-11-26",
    "length": 244,
    "keysig": ["D# / Cm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/headspace-ep",
    "art": "https://i1.sndcdn.com/artworks-D2rGnM5m3uqhPjbN-B117xw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 90,
    "title": "Two Sides",
    "subtitle": "",
    "release_date": "2021-11-26",
    "length": 248,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/headspace-ep",
    "art": "https://i1.sndcdn.com/artworks-D2rGnM5m3uqhPjbN-B117xw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 91,
    "title": "Psycho Battle",
    "subtitle": "",
    "release_date": "2021-11-26",
    "length": 242,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/headspace-ep",
    "art": "https://i1.sndcdn.com/artworks-D2rGnM5m3uqhPjbN-B117xw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 92,
    "title": "Forgive Yourself",
    "subtitle": "",
    "release_date": "2021-11-26",
    "length": 235,
    "keysig": ["E / C#m"],
    "tempo": [140],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/headspace-ep",
    "art": "https://i1.sndcdn.com/artworks-D2rGnM5m3uqhPjbN-B117xw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 93,
    "title": "We Don't Play",
    "subtitle": "Remix w/ Rushdown",
    "release_date": "2021-12-17",
    "length": 347,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "Disciple",
    "remix": true,
    "official": true,
    "collaboration": true,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://disc.fanlink.tv/TSBRCOAT",
    "art": "https://i1.sndcdn.com/artworks-BHdtdOpCK9iq4cfP-izmVPQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 94,
    "title": "We",
    "subtitle": "w/ Winamp Boys",
    "release_date": "2021-12-24",
    "length": 222,
    "keysig": ["G# / Fm"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": true,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://winamp.fanlink.tv/we",
    "art": "https://i1.sndcdn.com/artworks-57hfcGYzRvvN0Z0C-Paz1Dg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 95,
    "title": "Hold On",
    "subtitle": "",
    "release_date": "2022-1-28",
    "length": 212,
    "keysig": ["E / C#m"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://fanlink.tv/CBv3",
    "art": "https://i1.sndcdn.com/artworks-knupXkVX5BfYBlgx-ismRCw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 96,
    "title": "Choreography",
    "subtitle": "Chill Mix",
    "release_date": "2022-2-16",
    "length": 155,
    "keysig": ["C# / A#m"],
    "tempo": [105],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/moto1",
    "art": "https://i1.sndcdn.com/artworks-tVLiiWLMURuIi9zy-KKktwQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 97,
    "title": "Headspace",
    "subtitle": "Chill Mix",
    "release_date": "2022-2-16",
    "length": 197,
    "keysig": ["D / Bm"],
    "tempo": [90],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/moto1",
    "art": "https://i1.sndcdn.com/artworks-tVLiiWLMURuIi9zy-KKktwQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 98,
    "title": "Crescent",
    "subtitle": "Chill Mix",
    "release_date": "2022-2-16",
    "length": 220,
    "keysig": ["A / F#m"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/moto1",
    "art": "https://i1.sndcdn.com/artworks-tVLiiWLMURuIi9zy-KKktwQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 99,
    "title": "Shade Soul",
    "subtitle": "Chill Mix",
    "release_date": "2022-2-16",
    "length": 177,
    "keysig": ["F / Dm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/moto1",
    "art": "https://i1.sndcdn.com/artworks-tVLiiWLMURuIi9zy-KKktwQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 100,
    "title": "Visionary",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2022-3-16",
    "length": 279,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Heaven Sent",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://heavensent.ffm.to/unityremixes",
    "art": "https://i1.sndcdn.com/artworks-e54eIfcgP2Qj7Ben-jCkitA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 101,
    "title": "Blossom",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2022-6-9",
    "length": 287,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Proximity",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://proximity.ffm.to/memorygardenremix",
    "art": "https://i1.sndcdn.com/artworks-a5D6hbJCdZyjfNDk-CeYuuA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 102,
    "title": "Taking Control",
    "subtitle": "",
    "release_date": "2022-6-30",
    "length": 251,
    "keysig": ["A# / Gm"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/taking-control",
    "art": "https://i1.sndcdn.com/artworks-nvcazJzXmOyJBpS8-zwgV7Q-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 103,
    "title": "Crimson",
    "subtitle": "",
    "release_date": "2022-7-28",
    "length": 255,
    "keysig": ["F / Dm"],
    "tempo": [140],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/crimson",
    "art": "https://i1.sndcdn.com/artworks-zbjzuYPna7wVJrD6-GKyiwA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 104,
    "title": "Dreamer",
    "subtitle": "",
    "release_date": "2022-8-17",
    "length": 151,
    "keysig": ["F / Dm"],
    "tempo": [128],
    "label": "FORM",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://anv7.artbyform.com",
    "art": "https://i1.sndcdn.com/artworks-yDJ5VK1UxnpueLVD-8IJb5w-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 105,
    "title": "Sky Warrior",
    "subtitle": "",
    "release_date": "2022-9-8",
    "length": 215,
    "keysig": ["G / Em"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/sky-warrior",
    "art": "https://i1.sndcdn.com/artworks-EJCDEyZV6Zh60xrl-sqyzOg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 106,
    "title": "Nightmare",
    "subtitle": "",
    "release_date": "2022-10-13",
    "length": 247,
    "keysig": ["F / Dm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/nightmare",
    "art": "https://i1.sndcdn.com/artworks-MLczAONLylUq2LiV-4kj3mQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 107,
    "title": "Hometown",
    "subtitle": "Intro",
    "release_date": "2022-11-11",
    "length": 137,
    "keysig": ["A# / Gm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/generations",
    "art": "https://i1.sndcdn.com/artworks-KJ0JjQMqaqTsVau8-w8pyNw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 108,
    "title": "Runelord",
    "subtitle": "",
    "release_date": "2022-11-11",
    "length": 253,
    "keysig": ["A# / Gm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/generations",
    "art": "https://i1.sndcdn.com/artworks-KJ0JjQMqaqTsVau8-w8pyNw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 109,
    "title": "Pictomancer",
    "subtitle": "",
    "release_date": "2022-11-11",
    "length": 250,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/generations",
    "art": "https://i1.sndcdn.com/artworks-KJ0JjQMqaqTsVau8-w8pyNw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 110,
    "title": "Cherish",
    "subtitle": "",
    "release_date": "2022-11-11",
    "length": 249,
    "keysig": ["D / Bm"],
    "tempo": [120],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/generations",
    "art": "https://i1.sndcdn.com/artworks-KJ0JjQMqaqTsVau8-w8pyNw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 111,
    "title": "Farewell",
    "subtitle": "Outro",
    "release_date": "2022-11-11",
    "length": 198,
    "keysig": ["D / Bm"],
    "tempo": [60],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/generations",
    "art": "https://i1.sndcdn.com/artworks-KJ0JjQMqaqTsVau8-w8pyNw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 112,
    "title": "R.A.V.E.",
    "subtitle": "Remix",
    "release_date": "2023-2-15",
    "length": 241,
    "keysig": ["A / F#m"],
    "tempo": [140],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/rave-bootleg",
    "art": "https://i1.sndcdn.com/artworks-EZ9X2qESfJAYuUz1-yJo6Aw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 113,
    "title": "Shine",
    "subtitle": "",
    "release_date": "2023-6-1",
    "length": 237,
    "keysig": ["C# / A#m (+50ct)"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/shine",
    "art": "https://i1.sndcdn.com/artworks-r72yHkj3DPUly82J-UnObCg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 114,
    "title": "Luster Cries",
    "subtitle": "",
    "release_date": "2023-8-11",
    "length": 225,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/luster-cries",
    "art": "https://i1.sndcdn.com/artworks-EnI9ySegEmOCs4Pa-7YPFyw-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 115,
    "title": "Genjitsu Mysterium",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2023-8-25",
    "length": 286,
    "keysig": ["F# / D#m"],
    "tempo": [126],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/genjitsu-mysterium-remix",
    "art": "https://i1.sndcdn.com/artworks-XiEitG9M2z1IBHTH-oRBeag-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 116,
    "title": "(We Are) Friends",
    "subtitle": "w/ Winamp Boys",
    "release_date": "2023-11-20",
    "length": 272,
    "keysig": ["G# / Fm"],
    "tempo": [180],
    "label": "Independent",
    "remix": true,
    "official": true,
    "collaboration": true,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://soundcloud.com/bo-en/we-are-friends-bo-en-winamp-boys",
    "art": "https://i1.sndcdn.com/artworks-sSw9Pnkto8fFl4P4-Hp2hrA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 117,
    "title": "GUNK",
    "subtitle": "",
    "release_date": "2023-12-28",
    "length": 226,
    "keysig": ["G / Em"],
    "tempo": [150],
    "label": "Hypernight",
    "remix": false,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://soundcloud.com/similar-outskirts/gunk",
    "art": "https://i1.sndcdn.com/artworks-yJvrilzOZl7U881I-fev6hA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 118,
    "title": "Bling-Bang-Bang-Born",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2024-1-20",
    "length": 201,
    "keysig": ["C / Am"],
    "tempo": [145],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://youtu.be/bcuAK4y_bsw",
    "art": "https://i1.sndcdn.com/artworks-3aOB9zmyp6XKWEyU-N4Vtfg-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 119,
    "title": "All Ur Luv",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2024-5-10",
    "length": 210,
    "keysig": ["F / Dm"],
    "tempo": [126],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/all-ur-luv",
    "art": "https://i1.sndcdn.com/artworks-ghrb6vYzgm7i5Emf-Zxk36w-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 120,
    "title": "VOID",
    "subtitle": "Similar Outskirts Remix (ft. brenbread)",
    "release_date": "2024-7-24",
    "length": 293,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/void",
    "art": "https://i1.sndcdn.com/artworks-ymrXNckKiBnrbhz2-bylnpQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 121,
    "title": "Odo",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2024-8-27",
    "length": 238,
    "keysig": ["G# / Fm"],
    "tempo": [128],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/odo",
    "art": "https://i1.sndcdn.com/artworks-uNpPyzE1Mv6EGXVX-Zt1RyA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 122,
    "title": "UNDEAD",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2024-12-7",
    "length": 289,
    "keysig": ["F / Dm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": true,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/undead",
    "art": "https://i1.sndcdn.com/artworks-6mxhYr2xSQvOa3zL-Ql57RA-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 123,
    "title": "shake!the!city!",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2025-1-31",
    "length": 261,
    "keysig": ["G# / Fm"],
    "tempo": [128],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/shakethecity",
    "art": "https://i1.sndcdn.com/artworks-YdKdCjTnzoqUNJze-vAymyQ-t200x200.jpg",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 124,
    "title": "LUV ME",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2025-3-15",
    "length": 225,
    "keysig": ["E / C#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": true,
    "official": false,
    "collaboration": false,
    "anison": false,
    "yt_id": false,
    "license_info": "",
    "link": "https://music.similaroutskirts.com/luv-me",
    "art": "https://i1.sndcdn.com/artworks-jQrkYGsSvoUX17c5-uHBxyw-t200x200.png",
    "spotify": "",
    "apple_music": "",
    "soundcloud": "",
    "youtube": "",
    "bandcamp": "",
    "download": "",
  },
  {
    "id": 125,
    "title": "Koki Chant",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2025-3-20",
    "length": 257,
    "keysig": ["A# / Gm"],
    "tempo": [174],
    "label": "Independent",
    "remix": true,
    "official": true,
    "collaboration": false,
    "anison": false,
    "yt_id": true,
    "license_info": "",
    "link": "https://www.glacierofficial.com/music/kokichanttheremixes",
    "art": "https://i1.sndcdn.com/artworks-ihaluPHxi99kywe0-nzjG8w-t500x500.png",
    "spotify": "https://open.spotify.com/track/7bd7IaSSdhSR1or6wgU1K4?si=5a9fe4861e2846a2",
    "apple_music": "https://music.apple.com/us/album/koki-chant-similar-outskirts-remix/1800015178?i=1800015180",
    "soundcloud": "https://soundcloud.com/similar-outskirts/koki-chant",
    "youtube": "https://youtu.be/dXFC8UehnQE",
    "bandcamp": "https://glacierofficial.bandcamp.com/album/koki-chant-the-remixes",
    "download": "",
  },
]